# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'en-uk'

# Website info
name: 'Stray thoughts & keystrokes'
description: "Web log of various coding experiments and attempts"

# Author's info
author: 'Madhu kiran'
# edit 'categories' in the front matter of every post to match this username
nickname: madki
bio: 'Believes coding is a form of creative expression.'
location: 'Some City, India'
url: 'http://madki.xyz'
image: 'assets/images/madhukiran.jpg'

short_url: 'madki.xyz'
google_analytics: UA-73781008-1
disqus: madki
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /blog/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: madki
repo: blog
branch: master
relative_source: ../blog/
destination: ../blog-pages/
production_url:  https://madki.github.io/blog/
source_url:      https://github.com/madki/blog/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
